import java.time.LocalDate;

/**
 * Represents a trading signal generated by a strategy.
 * Contains the action (BUY/SELL/HOLD), price, and reasoning.
 *
 * @author Anthony Lewallen
 */
public class TradingSignal {

    public enum Action { BUY, SELL, HOLD }

    private final Action action;
    private final String symbol;
    private final double price;
    private final int quantity;
    private final LocalDate date;
    private final String strategy;
    private final String reason;
    private final double confidence;

    public TradingSignal(Action action, String symbol, double price, int quantity,
                         LocalDate date, String strategy, String reason, double confidence) {
        this.action = action;
        this.symbol = symbol;
        this.price = price;
        this.quantity = quantity;
        this.date = date;
        this.strategy = strategy;
        this.reason = reason;
        this.confidence = Math.min(1.0, Math.max(0.0, confidence));
    }

    public Action getAction() { return action; }
    public String getSymbol() { return symbol; }
    public double getPrice() { return price; }
    public int getQuantity() { return quantity; }
    public LocalDate getDate() { return date; }
    public String getStrategy() { return strategy; }
    public String getReason() { return reason; }
    public double getConfidence() { return confidence; }

    @Override
    public String toString() {
        String conf = String.format("%.0f%%", confidence * 100);
        return String.format("SIGNAL[%s %s %d @ $%.2f | %s | %s | confidence=%s]",
                action, symbol, quantity, price, strategy, reason, conf);
    }
}
